# Default values for nginx-gitops
# This is a YAML-formatted file.

# Image configuration
image:
  repository: taigavanilla/nginx-gitops
  tag: "4"
  pullPolicy: IfNotPresent
# Application configuration
app:
  name: nginx-gitops
  port: 80
  targetPort: 80
# Deployment configuration
deployment:
  replicas: 2
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 80
# Ingress configuration (optional)
ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: nginx-gitops.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
# Pod annotations
podAnnotations: {}
# Pod labels
podLabels: {}
# Node selector
nodeSelector: {}
# Tolerations
tolerations: []
# Affinity
affinity: {}
# Security context
securityContext: {}
# Container security context
containerSecurityContext: {}
# Service account
serviceAccount:
  create: true
  name: ""
# RBAC
rbac:
  create: false
