apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-gitops-monitor
  namespace: default
  labels:
    release: prometheus
    app: nginx-gitops
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-gitops
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
      honorLabels: true
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace
        - sourceLabels: [__meta_kubernetes_service_name]
          targetLabel: service
  namespaceSelector:
    matchNames:
      - default
